MaxEventSize = 25000  # Defines the maximum event size in kilobytes

[Writable]
PersistData = true
LogLevel = "DEBUG"
   [Writable.InsecureSecrets]
      [Writable.InsecureSecrets.DB]
         path = "iotdb"
            [Writable.InsecureSecrets.DB.Secrets]
            username = "root"
            password = "root"

[Service]
HealthCheckInterval = "10s"
Host = "localhost"
ServerBindAddr = ""  # blank value defaults to Service.Host value
Port = 59990
StartupMsg = "edgex-iotdb adapter service started"
# MaxRequestSize limit the request body size in byte of put command
MaxRequestSize = 0 # value 0 unlimit the request size.
RequestTimeout = "5s"
  [Service.CORSConfiguration]
  EnableCORS = false
  CORSAllowCredentials = false
  CORSAllowedOrigin = "https://localhost"
  CORSAllowedMethods = "GET, POST, PUT, PATCH, DELETE"
  CORSAllowedHeaders = "Authorization, Accept, Accept-Language, Content-Language, Content-Type, X-Correlation-ID"
  CORSExposeHeaders = "Cache-Control, Content-Language, Content-Length, Content-Type, Expires, Last-Modified, Pragma, X-Correlation-ID"
  CORSMaxAge = 3600

[Registry]
Host = "localhost"
Port = 8500
Type = "consul"

[MessageQueue]
Protocol = "redis"
Host = "localhost"
Port = 6379
Type = "redis"
AuthMode = "none"  # required for redis messagebus (secure or insecure).
SecretName = "redisdb"
PublishTopicPrefix = "edgex/events/core"
SubscribeTopic = "edgex/events/device/#"  # /<device-profile-name>/<device-name>/<source-name> will be added to this Publish Topic prefix
  [MessageQueue.Optional]
  # Default MQTT Specific options that need to be here to enable environment variable overrides of them
  # Client Identifiers
  ClientId = "iotdb-connector"
  # Connection information
  Qos = "0" # Quality of Sevice values are 0 (At most once), 1 (At least once) or 2 (Exactly once)
  KeepAlive = "10" # Seconds (must be 2 or greater)
  Retained = "false"
  AutoReconnect = "true"
  ConnectTimeout = "5" # Seconds
  SkipCertVerify = "false" # Only used if Cert/Key file or Cert/Key PEMblock are specified

[Databases]
  [Databases.Primary]
  Host = "localhost"
  Name = "iotdb"
  Password = "root"
  Username = "root"
  Port = 6667
  Timeout = 5000
  Type = "iotdb"

[IoTDB]
Host = "localhost"
Port = 6379
UserName = ""
Password = ""
  [IoTDB.Optional]
    Encoding = "PLAIN" #PLAIN, TS_2DIFF, RLE, GORILLA, DICTIONARY, FREQ
    Compressor = "" #UNCOMPRESSED, SNAPPY, LZ4, GZIP
  